
import java.awt.Color;
import java.text.DecimalFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author israelbeh
 * Description: This program calculates the GPA for the IS program pre-reqs. 
 * The user is able to select the grades from a drop down menu. When the Calc GPA
 * button is clicked, the GPA is calculated
 */
    
public class Pjt2_Beh extends javax.swing.JFrame {

    /**
     * Creates new form Pjt2_Beh
     */
    public Pjt2_Beh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlTop = new javax.swing.JPanel();
        LblTop = new javax.swing.JLabel();
        LblName = new javax.swing.JLabel();
        TxtFldName = new javax.swing.JTextField();
        PnlLeft = new javax.swing.JPanel();
        LblEntGrd = new javax.swing.JLabel();
        Lblis100 = new javax.swing.JLabel();
        Lblis102 = new javax.swing.JLabel();
        Lblis201 = new javax.swing.JLabel();
        Lblis303 = new javax.swing.JLabel();
        Lblacc200 = new javax.swing.JLabel();
        Lblfin201 = new javax.swing.JLabel();
        Lblbusm241 = new javax.swing.JLabel();
        Lblcrs = new javax.swing.JLabel();
        Lblcdts = new javax.swing.JLabel();
        Lblgrd = new javax.swing.JLabel();
        txtfldis100 = new javax.swing.JTextField();
        txtfldis102 = new javax.swing.JTextField();
        txtfldis201 = new javax.swing.JTextField();
        txtfldis303 = new javax.swing.JTextField();
        txtfldacc200 = new javax.swing.JTextField();
        txtfldfin201 = new javax.swing.JTextField();
        txtfldbusm241 = new javax.swing.JTextField();
        CboxIS100 = new javax.swing.JComboBox();
        CboxIS102 = new javax.swing.JComboBox();
        CboxIS201 = new javax.swing.JComboBox();
        CboxIS303 = new javax.swing.JComboBox();
        CboxAcc200 = new javax.swing.JComboBox();
        CboxFIN201 = new javax.swing.JComboBox();
        CboxBusm241 = new javax.swing.JComboBox();
        BtnCalcGPA = new javax.swing.JButton();
        BtnReset = new javax.swing.JButton();
        PnlRight = new javax.swing.JPanel();
        LblGPA = new javax.swing.JLabel();
        LblCalcGPA = new javax.swing.JLabel();
        PnlGreen = new javax.swing.JPanel();
        PnlYellow = new javax.swing.JPanel();
        PnlRed = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlTop.setBackground(new java.awt.Color(51, 153, 255));
        PnlTop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PnlTop.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        LblTop.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        LblTop.setForeground(new java.awt.Color(255, 255, 255));
        LblTop.setText("IS Pre-Req GPA Calculator");

        LblName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LblName.setForeground(new java.awt.Color(255, 255, 255));
        LblName.setText("Enter Your Name");

        javax.swing.GroupLayout PnlTopLayout = new javax.swing.GroupLayout(PnlTop);
        PnlTop.setLayout(PnlTopLayout);
        PnlTopLayout.setHorizontalGroup(
            PnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTopLayout.createSequentialGroup()
                .addGroup(PnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlTopLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(LblTop, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlTopLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(LblName)
                        .addGap(18, 18, 18)
                        .addComponent(TxtFldName, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        PnlTopLayout.setVerticalGroup(
            PnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTopLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(LblTop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblName)
                    .addComponent(TxtFldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(PnlTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 564, -1));

        PnlLeft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LblEntGrd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LblEntGrd.setText("Enter Grades");

        Lblis100.setText("IS 100");

        Lblis102.setText("IS 102");

        Lblis201.setText("IS 201");

        Lblis303.setText("IS 303");

        Lblacc200.setText("ACC 200");

        Lblfin201.setText("FIN 201");

        Lblbusm241.setText("BUSM 241");

        Lblcrs.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Lblcrs.setText("Course");

        Lblcdts.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Lblcdts.setText("Credits");

        Lblgrd.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Lblgrd.setText("Grade");

        txtfldis100.setText(".5");

        txtfldis102.setText(".5");

        txtfldis201.setText("3");

        txtfldis303.setText("3");

        txtfldacc200.setText("3");

        txtfldfin201.setText("3");

        txtfldbusm241.setText("3");

        CboxIS100.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E", " " }));
        CboxIS100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboxIS100ActionPerformed(evt);
            }
        });

        CboxIS102.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));

        CboxIS201.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));

        CboxIS303.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));

        CboxAcc200.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));

        CboxFIN201.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));

        CboxBusm241.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "E" }));

        BtnCalcGPA.setText("Calc GPA");
        BtnCalcGPA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCalcGPAMouseClicked(evt);
            }
        });
        BtnCalcGPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcGPAActionPerformed(evt);
            }
        });

        BtnReset.setText("Reset");
        BtnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnResetMouseClicked(evt);
            }
        });
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlLeftLayout = new javax.swing.GroupLayout(PnlLeft);
        PnlLeft.setLayout(PnlLeftLayout);
        PnlLeftLayout.setHorizontalGroup(
            PnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PnlLeftLayout.createSequentialGroup()
                        .addGroup(PnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Lblis201)
                            .addComponent(Lblis303)
                            .addComponent(Lblis102)
                            .addComponent(LblEntGrd)
                            .addComponent(Lblis100))
                        .addGap(57, 57, 57)
                        .addGroup(PnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfldis102, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfldis201, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BtnCalcGPA)
                        .addGroup(PnlLeftLayout.createSequentialGroup()
                            .addGroup(PnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Lblcrs)
                                .addComponent(Lblacc200)
                                .addComponent(Lblfin201)
                                .addComponent(Lblbusm241))
                            .addGap(34, 34, 34)
                            .addGroup(PnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtfldis303)
                                .addComponent(txtfldis100)
                                .addComponent(Lblcdts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtfldacc200)
                                .addComponent(txtfldfin201)
                                .addComponent(txtfldbusm241)))))
                .addGroup(PnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlLeftLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(PnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CboxBusm241, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CboxFIN201, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CboxAcc200, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CboxIS303, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CboxIS201, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CboxIS102, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CboxIS100, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnReset))
                        .addGap(27, 27, 27))
                    .addGroup(PnlLeftLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Lblgrd)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PnlLeftLayout.setVerticalGroup(
            PnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblEntGrd)
                .addGap(58, 58, 58)
                .addGroup(PnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lblcrs)
                    .addComponent(Lblcdts)
                    .addComponent(Lblgrd))
                .addGap(18, 18, 18)
                .addGroup(PnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lblis100)
                    .addComponent(txtfldis100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CboxIS100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lblis102, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfldis102, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CboxIS102, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lblis201)
                    .addComponent(txtfldis201, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CboxIS201, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lblis303, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfldis303, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CboxIS303, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lblacc200)
                    .addComponent(txtfldacc200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CboxAcc200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lblfin201)
                    .addComponent(txtfldfin201, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CboxFIN201, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lblbusm241)
                    .addComponent(txtfldbusm241, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CboxBusm241, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(PnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCalcGPA)
                    .addComponent(BtnReset))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(PnlLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 119, -1, 536));

        PnlRight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PnlRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblGPA.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LblGPA.setText("GPA");
        PnlRight.add(LblGPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 22, -1, -1));

        LblCalcGPA.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PnlRight.add(LblCalcGPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 61, 91, 19));

        javax.swing.GroupLayout PnlGreenLayout = new javax.swing.GroupLayout(PnlGreen);
        PnlGreen.setLayout(PnlGreenLayout);
        PnlGreenLayout.setHorizontalGroup(
            PnlGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );
        PnlGreenLayout.setVerticalGroup(
            PnlGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        PnlRight.add(PnlGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        javax.swing.GroupLayout PnlYellowLayout = new javax.swing.GroupLayout(PnlYellow);
        PnlYellow.setLayout(PnlYellowLayout);
        PnlYellowLayout.setHorizontalGroup(
            PnlYellowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );
        PnlYellowLayout.setVerticalGroup(
            PnlYellowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        PnlRight.add(PnlYellow, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        javax.swing.GroupLayout PnlRedLayout = new javax.swing.GroupLayout(PnlRed);
        PnlRed.setLayout(PnlRedLayout);
        PnlRedLayout.setHorizontalGroup(
            PnlRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );
        PnlRedLayout.setVerticalGroup(
            PnlRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        PnlRight.add(PnlRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        getContentPane().add(PnlRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 250, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CboxIS100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxIS100ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboxIS100ActionPerformed

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnResetActionPerformed

    private void BtnCalcGPAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCalcGPAMouseClicked
      
    }//GEN-LAST:event_BtnCalcGPAMouseClicked
  
    
    private void BtnCalcGPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcGPAActionPerformed
       DecimalFormat dFormat = new DecimalFormat("0.00");   //sets the format for the final display of the GPA    
       double dTotal=0;
       //these variables are used to capture the weight calculated in the
       //method CalcGPA
       double dWeightIS100;
       double dWeightIS102;
       double dWeightIS201;
       double dWeightIS303;
       double dWeightACC200;
       double dWeightFIN201;
       double dWeightBUSM241;
     
       
       Student aoStud = new Student();//create a student object
       //call the methods for each class and calculate the weights.
       dWeightIS100 = aoStud.CalcGPA(String.valueOf(CboxIS100.getSelectedItem()), Double.parseDouble(txtfldis100.getText()));
       dWeightIS102 = aoStud.CalcGPA(String.valueOf(CboxIS102.getSelectedItem()), Double.parseDouble(txtfldis102.getText()));
       dWeightIS201 = aoStud.CalcGPA(String.valueOf(CboxIS201.getSelectedItem()), Double.parseDouble(txtfldis201.getText()));
       dWeightIS303 = aoStud.CalcGPA(String.valueOf(CboxIS303.getSelectedItem()), Double.parseDouble(txtfldis303.getText()));
       dWeightACC200 = aoStud.CalcGPA(String.valueOf(CboxAcc200.getSelectedItem()), Double.parseDouble(txtfldacc200.getText()));
       dWeightFIN201 = aoStud.CalcGPA(String.valueOf(CboxFIN201.getSelectedItem()), Double.parseDouble(txtfldfin201.getText()));
       dWeightBUSM241 = aoStud.CalcGPA(String.valueOf(CboxBusm241.getSelectedItem()), Double.parseDouble(txtfldbusm241.getText()));
       
       //calculate overall GPA
       dTotal = (dWeightIS100 + dWeightIS102 + dWeightIS201 + dWeightIS303 + dWeightACC200 + dWeightFIN201 + dWeightBUSM241)/ 
                (Double.parseDouble(txtfldis100.getText()) + Double.parseDouble(txtfldis102.getText()) + 
                 Double.parseDouble(txtfldis201.getText()) + Double.parseDouble(txtfldis303.getText()) + 
                 Double.parseDouble(txtfldacc200.getText()) + Double.parseDouble(txtfldfin201.getText()) 
                 + Double.parseDouble(txtfldbusm241.getText()));
       //displays the GPA with two decimal points
       LblCalcGPA.setText(dFormat.format(dTotal));
               
        //Displays green, yellow, or red      
        if (dTotal >= 3.7)
        {
            PnlGreen.setBackground(Color.GREEN);
            PnlGreen.setVisible(true);
            PnlYellow.setVisible(false);
            PnlRed.setVisible(false);
        }
        else if ( dTotal >= 3.3 && dTotal < 3.7)
        {
            PnlGreen.setVisible(false);
            PnlYellow.setBackground(Color.yellow);
            PnlYellow.setVisible(true);
            PnlRed.setVisible(false);
        }
        else
        {
            PnlGreen.setVisible(false);
            PnlRed.setBackground(Color.red);
            PnlRed.setVisible(true);
            PnlYellow.setVisible(false);
        }
 
    }//GEN-LAST:event_BtnCalcGPAActionPerformed

    private void BtnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnResetMouseClicked
        // Resets all of the Values
       LblCalcGPA.setText("0.00");
       PnlGreen.setVisible(false);
       PnlYellow.setVisible(false);
       PnlRed.setVisible(false);
       CboxIS100.setSelectedItem(0);
       CboxIS102.setSelectedItem(0);
       CboxIS201.setSelectedItem(0);
       CboxIS303.setSelectedItem(0);
       CboxAcc200.setSelectedItem(0);
       CboxBusm241.setSelectedItem(0);
       TxtFldName.setText(null);
       TxtFldName.requestFocus();
    }//GEN-LAST:event_BtnResetMouseClicked
                                      
                          
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pjt2_Beh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pjt2_Beh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pjt2_Beh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pjt2_Beh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pjt2_Beh().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCalcGPA;
    private javax.swing.JButton BtnReset;
    private javax.swing.JComboBox CboxAcc200;
    private javax.swing.JComboBox CboxBusm241;
    private javax.swing.JComboBox CboxFIN201;
    private javax.swing.JComboBox CboxIS100;
    private javax.swing.JComboBox CboxIS102;
    private javax.swing.JComboBox CboxIS201;
    private javax.swing.JComboBox CboxIS303;
    private javax.swing.JLabel LblCalcGPA;
    private javax.swing.JLabel LblEntGrd;
    private javax.swing.JLabel LblGPA;
    private javax.swing.JLabel LblName;
    private javax.swing.JLabel LblTop;
    private javax.swing.JLabel Lblacc200;
    private javax.swing.JLabel Lblbusm241;
    private javax.swing.JLabel Lblcdts;
    private javax.swing.JLabel Lblcrs;
    private javax.swing.JLabel Lblfin201;
    private javax.swing.JLabel Lblgrd;
    private javax.swing.JLabel Lblis100;
    private javax.swing.JLabel Lblis102;
    private javax.swing.JLabel Lblis201;
    private javax.swing.JLabel Lblis303;
    private javax.swing.JPanel PnlGreen;
    private javax.swing.JPanel PnlLeft;
    private javax.swing.JPanel PnlRed;
    private javax.swing.JPanel PnlRight;
    private javax.swing.JPanel PnlTop;
    private javax.swing.JPanel PnlYellow;
    private javax.swing.JTextField TxtFldName;
    private javax.swing.JTextField txtfldacc200;
    private javax.swing.JTextField txtfldbusm241;
    private javax.swing.JTextField txtfldfin201;
    private javax.swing.JTextField txtfldis100;
    private javax.swing.JTextField txtfldis102;
    private javax.swing.JTextField txtfldis201;
    private javax.swing.JTextField txtfldis303;
    // End of variables declaration//GEN-END:variables
}
