
import java.text.DecimalFormat;
import javax.swing.JCheckBox;

/**
 *
 * @author israelbeh
 * Description: this program allows the user to calculate a Home Teaching 
 * percentage by allowing the user to check the companion box when the HT is 
 * completed. The user is also able to reset the the boxes and percentage making
 * multiple uses possible. The user may also close the program by clicking the end
 * button.
 */
public class HomeTeaching extends javax.swing.JFrame {

    /**
     * Creates new form HomeTeaching
     */
    public HomeTeaching() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlMain = new javax.swing.JPanel();
        LblName = new javax.swing.JLabel();
        ChkbxHT1 = new javax.swing.JCheckBox();
        ChkbxHT2 = new javax.swing.JCheckBox();
        ChkbxHT3 = new javax.swing.JCheckBox();
        ChkbxHT4 = new javax.swing.JCheckBox();
        ChkbxHT5 = new javax.swing.JCheckBox();
        ChkbxHT6 = new javax.swing.JCheckBox();
        ChkbxHT7 = new javax.swing.JCheckBox();
        ChkbxHT8 = new javax.swing.JCheckBox();
        ChkbxHT9 = new javax.swing.JCheckBox();
        ChkbxHT10 = new javax.swing.JCheckBox();
        BtnCalcHT = new javax.swing.JButton();
        BtnEnd = new javax.swing.JButton();
        LblHTPct = new javax.swing.JLabel();
        LblCalcPct = new javax.swing.JLabel();
        BtnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlMain.setBackground(new java.awt.Color(0, 153, 153));
        PnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        LblName.setForeground(new java.awt.Color(204, 204, 0));
        LblName.setText("Home Teaching Calculator");
        PnlMain.add(LblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        ChkbxHT1.setForeground(new java.awt.Color(255, 255, 0));
        ChkbxHT1.setText("King James/ King David");
        ChkbxHT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkbxHT1ActionPerformed(evt);
            }
        });
        PnlMain.add(ChkbxHT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        ChkbxHT2.setForeground(new java.awt.Color(255, 255, 0));
        ChkbxHT2.setText("Brother of Jared/ Ammon");
        PnlMain.add(ChkbxHT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        ChkbxHT3.setForeground(new java.awt.Color(255, 255, 0));
        ChkbxHT3.setText("Nephi/ Sam");
        PnlMain.add(ChkbxHT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        ChkbxHT4.setForeground(new java.awt.Color(255, 255, 0));
        ChkbxHT4.setText("Lamen/ Lemuel");
        PnlMain.add(ChkbxHT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        ChkbxHT5.setForeground(new java.awt.Color(255, 255, 0));
        ChkbxHT5.setText("Lehi/ King Noah");
        PnlMain.add(ChkbxHT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        ChkbxHT6.setForeground(new java.awt.Color(255, 255, 0));
        ChkbxHT6.setText("Jacob/ Joseph");
        PnlMain.add(ChkbxHT6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        ChkbxHT7.setForeground(new java.awt.Color(255, 255, 0));
        ChkbxHT7.setText("Moroni/ Mormon");
        PnlMain.add(ChkbxHT7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        ChkbxHT8.setForeground(new java.awt.Color(255, 255, 0));
        ChkbxHT8.setText("John/ Peter");
        PnlMain.add(ChkbxHT8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        ChkbxHT9.setForeground(new java.awt.Color(255, 255, 0));
        ChkbxHT9.setText("Noah/ Abraham");
        PnlMain.add(ChkbxHT9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        ChkbxHT10.setForeground(new java.awt.Color(255, 255, 0));
        ChkbxHT10.setText("Paul/ Abinadi");
        PnlMain.add(ChkbxHT10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        BtnCalcHT.setForeground(new java.awt.Color(0, 153, 153));
        BtnCalcHT.setText("Calculate");
        BtnCalcHT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCalcHTMouseClicked(evt);
            }
        });
        PnlMain.add(BtnCalcHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 100, -1));

        BtnEnd.setForeground(new java.awt.Color(0, 153, 153));
        BtnEnd.setText("End");
        BtnEnd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEndMouseClicked(evt);
            }
        });
        PnlMain.add(BtnEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 90, -1));

        LblHTPct.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LblHTPct.setForeground(new java.awt.Color(204, 204, 0));
        LblHTPct.setText("Home Teaching Percentage:");
        PnlMain.add(LblHTPct, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        LblCalcPct.setForeground(new java.awt.Color(255, 255, 0));
        PnlMain.add(LblCalcPct, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 100, 20));

        BtnReset.setForeground(new java.awt.Color(0, 153, 153));
        BtnReset.setText("Reset");
        BtnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnResetMouseClicked(evt);
            }
        });
        PnlMain.add(BtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 90, -1));

        getContentPane().add(PnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 393, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChkbxHT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkbxHT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChkbxHT1ActionPerformed
   
    private void BtnCalcHTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCalcHTMouseClicked
       DecimalFormat dFormat = new DecimalFormat("0.00");//rounds the percentage to 2 decimals
       DecimalFormat drFormat = new DecimalFormat("0");//allows the percentage to be displayed as a whole number
       
       int iCount;
       int iTotal = 0;
       double dPercentage = 0;
       
     //the array holds the checkboxes
     JCheckBox aChkBxHT[] = {ChkbxHT1, ChkbxHT2, ChkbxHT3, ChkbxHT4, ChkbxHT5,
       ChkbxHT6, ChkbxHT7, ChkbxHT8, ChkbxHT9, ChkbxHT10};
   //the for loop goes through each check box
        for (iCount = 0; iCount < aChkBxHT.length; iCount++)
        {
            //the if statement verifies if the checkbox is selected
         if (aChkBxHT[iCount].isSelected())
         {
              iTotal +=1;
         }
        else
            iTotal += 0;
        }
    // dPercentage holds the percentage of HT that is checked.
    dPercentage = (double) iTotal / aChkBxHT.length;
    dFormat.format(dPercentage);
    dPercentage = dPercentage*100;//makes the percentage a whole number.
    LblCalcPct.setText((drFormat.format(dPercentage)) + " %");
    }//GEN-LAST:event_BtnCalcHTMouseClicked

    private void BtnEndMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEndMouseClicked
        // TODO closes the program
        System.exit(0);
    }//GEN-LAST:event_BtnEndMouseClicked

    private void BtnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnResetMouseClicked
    
        int iCount;
   
       JCheckBox aChkBxHT[] = {ChkbxHT1, ChkbxHT2, ChkbxHT3, ChkbxHT4, ChkbxHT5,
       ChkbxHT6, ChkbxHT7, ChkbxHT8, ChkbxHT9, ChkbxHT10};
       // for loop goes through the array of checkboxes
        for (iCount = 0; iCount < aChkBxHT.length; iCount++)
        {
            //the if statement reset the checkbox as unchecked
            if (aChkBxHT[iCount].isSelected())
            {
                aChkBxHT[iCount].setSelected(false);// unchecks the boxes
            }
        }
    
        LblCalcPct.setText(null);// resets the perentage
    
    }//GEN-LAST:event_BtnResetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeTeaching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeTeaching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeTeaching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeTeaching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeTeaching().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCalcHT;
    private javax.swing.JButton BtnEnd;
    private javax.swing.JButton BtnReset;
    private javax.swing.JCheckBox ChkbxHT1;
    private javax.swing.JCheckBox ChkbxHT10;
    private javax.swing.JCheckBox ChkbxHT2;
    private javax.swing.JCheckBox ChkbxHT3;
    private javax.swing.JCheckBox ChkbxHT4;
    private javax.swing.JCheckBox ChkbxHT5;
    private javax.swing.JCheckBox ChkbxHT6;
    private javax.swing.JCheckBox ChkbxHT7;
    private javax.swing.JCheckBox ChkbxHT8;
    private javax.swing.JCheckBox ChkbxHT9;
    private javax.swing.JLabel LblCalcPct;
    private javax.swing.JLabel LblHTPct;
    private javax.swing.JLabel LblName;
    private javax.swing.JPanel PnlMain;
    // End of variables declaration//GEN-END:variables

}

